services:

  portainer:

    image: ${PORTAINER_REGISTRY}/portainer/portainer-ce:lts
    container_name: portainer
    restart: unless-stopped
    ports:
    - 9443:9443
    - 8000:8000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:Z
    - portainer_data:/data

  agent:
  
    image: ${PORTAINER_REGISTRY}/portainer/agent:lts
    container_name: portainer-agent
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

volumes:
  portainer_data:
    name: portainer_data
