services:

  registry:

    image: docker.io/library/registry:latest
    container_name: registry
    restart: unless-stopped
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - registry_data:/var/lib/registry
    ports:
      - 5000:5000

  registry-ui:

    depends_on:
      - registry
    image: myreg.local/utils/registry-ui:latest
    container_name: registry-ui
    restart: unless-stopped
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Local Registry
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    ports:
      - 8088:80

  portainer:

    depends_on:
      - registry
    image: myreg.local/utils/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      # Working on all systems at this point as long as the uid is correct
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:Z
      
      # Works on WSL and ubuntu 
      # - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock:Z

      # Works on MacOS with --rootful on the init
      # - /run/podman/podman.sock:/var/run/docker.sock:Z

      - portainer_data:/data
    ports:
      - 9443:9444
      - 8000:8000

volumes:
  registry_data:
    name: podman_registry_data
  portainer_data:
    name: podman_portainer_data
