services:

  agent:
      image: ${PORTAINER_REGISTRY}/portainer/agent:latest
      container_name: portainer
      restart: unless-stopped
      ports:
        - "9001:9001"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/lib/docker/volumes:/var/lib/docker/volumes
