services:

  portainer:

    image: ${PORTAINER_REGISTRY}/portainer/portainer-ce:lts
    container_name: portainer
    restart: unless-stopped
    ports:
    - 9443:9443
    - 8000:8000
    volumes:
    # Working on wsl2 docker
    - /var/run/docker.sock:/var/run/docker.sock:Z
    - portainer_data:/data

volumes:
  portainer_data:
    name: portainer_data
