---
services:
  openshot:
    image: linuxserver/openshot:latest
    container_name: openshot
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/rc120846/Projects/Video/openshot/config:/config
      - /home/rc120846/Projects/Video:/data
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
