# Personal zsh customizations

# Find out where this script is located

HERE=${0:a:h:h}

# Avoid duplicates

typeset -U PATH path manpath

# Set platform dependent variables

case $OSTYPE in
    darwin*)

	    LDLIB=DYLD_LIBRARY_PATH
	    export TIME="/usr/bin/time -l"
        
        # Disable automatic cleanup
        export HOMEBREW_NO_INSTALL_CLEANUP=1

        # Homebrew paths

        if [ -d /usr/local/opt/coreutils/libexec ]; then
            path=(/usr/local/opt/coreutils/libexec/gnubin $path)
            manpath=(/usr/local/opt/coreutils/libexec/gnuman $manpath)
        fi 

        # MacTeX
        [ -d /Library/TeX/texbin ] && path=(/Library/TeX/texbin $path)

        # Man pages output to skim
        manp()
        {
            man -t "${1}" | open -f -a Skim
        }

        # Homebrew
        [ -f /opt/homebrew/bin/brew ] && eval $(/opt/homebrew/bin/brew shellenv)

        ;;

    linux*)
        
	    LDLIB=LD_LIBRARY_PATH
	    export TIME="/usr/bin/time --verbose"

        # Set the display for wsl
        [[ $(uname -a) == *WSL* ]] && export DISPLAY=$(route -n | grep UG | head -n1 | awk '{print $2}'):0
        
        ;;

esac

# My directories

path=(~/.local/bin $path)
manpath=(~/.local/share/man $manpath)

# Rust
[ -d ~/.cargo/bin ] && path=(~/.cargo/bin $path)

# Direnv
[ $(command -v direnv) ] && eval "$(direnv hook zsh)"

# Python

PVE=~/.local/PVE

pushd $PVE &> /dev/null

for d in *(N) 
    alias ${d%/}="source $PVE/${d%/}/bin/activate"

popd &> /dev/null

[ -d $HERE/python ] && export PYTHONPATH=$HERE/python

# Since all we're using pyenv for is getting python distributions 
# we don't actually install the hooks

[ -d ~/.pyenv ] && export PYENV_ROOT=~/.pyenv
[ -d ~/.pyenv/bin ] && export path=(~/.pyenv/bin $path)

# Aliases

pprint() {
    for v in ${(P)1}; echo $v
}

alias l=less 

# Default editor
[ $(command -v nano) ] && {
    export EDITOR=$(which nano)
    export VISUAL=$(which nano)
}

# Set emacs editing mode
bindkey -e
