- name: Install stuff into linux with a restricted sudo
  hosts: localhost
  vars:
    the_user: "{{ ansible_user_id }}"
    ansible_sudo_pass: Halbert^^279
    pycurrent: 3.13.1

  tasks:

  - include_tasks: "includes/{{ ansible_facts['distribution'] }}_restricted_packages.yaml"
  # - import_tasks: includes/change_shell.yaml
  - import_tasks: includes/oh-my-zsh.yaml
  - import_tasks: includes/ssh_keys.yaml
  - import_tasks: includes/config_files.yaml
  # - import_tasks: includes/install_python.yaml
  # - import_tasks: includes/gnome_customization.yaml
