- name: tmux powerline setup
  hosts: provision_ssh
  tasks:

  - name: Clone tpm
    git:
      repo: https://github.com/tmux-plugins/tpm 
      dest: ~/.tmux/plugins/tpm

  - name: Create directories
    file:
      path: "{{item}}"
      state: directory
    loop:
      "{{ links }}"
    vars:
      links:
        - ~/.config

  - name: Remove old links
    file:
      path: "{{item}}"
      state: absent
    loop:
      "{{ links }}"
    vars:
      links:
        - ~/.tmux.conf
        - ~/.config/tmux-powerline

  - name: Symlink Stuff
    file:
      src: "{{item.value}}"
      dest: "{{item.key}}"
      state: link
    loop:
      "{{ links | dict2items }}"
    vars:
      links:
        ~/.tmux.conf: 
          ~/Projects/SharedEnvironment/tmux/.tmux.tpm.conf
        ~/.config/tmux-powerline: 
          ~/Projects/SharedEnvironment/tmux/tmux-powerline
