- name: ssh based setup
  hosts: provision_ssh
  tasks:

  - name: Download oh-my-zsh
    get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: /tmp/oh-my-zsh.sh
      mode: '0777'

  - name: Install oh-my-zsh
    command:
      cmd: /tmp/oh-my-zsh.sh --unattended
      creates: ~/.oh-my-zsh

  - name: Create projects directory
    file:
      path: ~/Projects
      state: directory

  - name: symlink stuff
    file:
      src: "{{item.value}}"
      dest: "{{item.key}}"
      state: link
    loop:
      "{{ links | dict2items }}"
    vars:
      links:
        ~/Projects/SharedEnvironment: 
          /mnt/SharedEnvironment
        ~/.tmux.conf: 
          ~/Projects/SharedEnvironment/tmux/.tmux.conf

  - name: Add connection to my updates
    lineinfile:
      path: ~/.zshrc
      create: no
      line: "{{ item }}"
      insertbefore: "^source.*oh-my-zsh.sh$"
    loop:
      - ZSH_THEME="bowser"
      - ZSH_CUSTOM=~/Projects/SharedEnvironment/zsh
      - plugins=(virtualenv)
      - source $ZSH_CUSTOM/.zshrc

