- name: Install utilities
  become: yes
  apt:
    update_cache: true
    pkg:
      - aptitude
      - direnv
      - htop
      - net-tools
      - tmux
      - mc
      - podman
      - openssh-server
      - zsh

- name: Packages not to be installed in wsl
  become: yes
  when: ansible_virtualization_type != "wsl"
  block:

  - name: Add brave gpg key
    become: yes
    apt_key:
      url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
      state: present

  - name: Add brave repo
    become: yes
    apt_repository:
      repo: "deb https://brave-browser-apt-release.s3.brave.com/ stable main"


  - name: Additional packages
    become: yes
    apt:
      pkg:
        - avahi-utils
        - brave-browser